"""事件类型常量。

所有状态变化都以追加事件表达，事件不可修改、不可删除，
按 ``seq`` 形成全局哈希链（见 :mod:`risk_service.store`）。
"""
from __future__ import annotations

# 规则集发布（规则有版本、有生效时间）
RULESET_PUBLISHED = "RULESET_PUBLISHED"

# 风险登记六要素：来源、影响对象、责任人、缓解措施、限制动作、复查日期
RISK_REGISTERED = "RISK_REGISTERED"
MITIGATION_UPDATED = "MITIGATION_UPDATED"

# 评级（每次评级快照规则版本、得分、命中规则）
RISK_RATED = "RISK_RATED"
# 评级下降导致的限制自动解除，构成“降级”决定链
RISK_DOWNGRADED = "RISK_DOWNGRADED"

# 限制动作及其解除
RISK_CONTROL_ADDED = "RISK_CONTROL_ADDED"
RESTRICTION_RELEASED = "RESTRICTION_RELEASED"
FLOW_RESTORED = "FLOW_RESTORED"

# 例外批准 / 撤销 / 到期失效
EXCEPTION_GRANTED = "EXCEPTION_GRANTED"
EXCEPTION_REVOKED = "EXCEPTION_REVOKED"
EXCEPTION_EXPIRED = "EXCEPTION_EXPIRED"

# 风险合并（源风险并入目标风险）
RISK_MERGED = "RISK_MERGED"

# 定时复查
RISK_REVIEW_DUE = "RISK_REVIEW_DUE"
RISK_REVIEWED = "RISK_REVIEWED"

# 关闭与复开
RISK_CLOSED = "RISK_CLOSED"
RISK_REOPENED = "RISK_REOPENED"

#: 风险生命周期状态
STATUS_OPEN = "OPEN"
STATUS_MERGED = "MERGED"
STATUS_CLOSED = "CLOSED"

#: 限制动作
ACTION_HALT_ENROLLMENT = "暂停招生"
ACTION_FREEZE_PAYMENT = "冻结付款"
ACTION_HOLD_MILESTONE = "暂停里程碑"
ACTIONS = (ACTION_HALT_ENROLLMENT, ACTION_FREEZE_PAYMENT, ACTION_HOLD_MILESTONE)

#: 限制动作传播到的下游流程
FLOW_ENROLLMENT = "招生"
FLOW_PAYMENT = "付款"
FLOW_MILESTONE = "里程碑"
FLOWS = (FLOW_ENROLLMENT, FLOW_PAYMENT, FLOW_MILESTONE)

#: 动作 -> 受其门禁的流程
ACTION_FLOW = {
    ACTION_HALT_ENROLLMENT: FLOW_ENROLLMENT,
    ACTION_FREEZE_PAYMENT: FLOW_PAYMENT,
    ACTION_HOLD_MILESTONE: FLOW_MILESTONE,
}
FLOW_ACTION = {flow: action for action, flow in ACTION_FLOW.items()}

#: 限制来源：评级规则触发 / 登记时预案 / 手工升级 / 合并带入
ORIGIN_RULE = "RULE"
ORIGIN_PLAN = "PLAN"
ORIGIN_MANUAL = "MANUAL"
ORIGIN_MERGE = "MERGE"

#: 例外状态
EXC_ACTIVE = "ACTIVE"
EXC_REVOKED = "REVOKED"
EXC_EXPIRED = "EXPIRED"

#: 复查结论
REVIEW_CONFIRMED = "CONFIRMED"
REVIEW_ADJUSTED = "ADJUSTED"
REVIEW_RESOLVED = "RESOLVED"

#: 门禁结论
GATE_ALLOWED = "ALLOWED"
GATE_ALLOWED_WITH_EXCEPTION = "ALLOWED_WITH_EXCEPTION"
GATE_BLOCKED = "BLOCKED"

#: 作用于该流程的全部对象（通配）
TARGET_ALL = "*"
